# Registry-wide mirror for everything under docker.io (fallback for repos without a specific mapping)
apiVersion: qebbeq.tuco86.dev/v1alpha1
kind: ImageMirror
metadata:
  name: docker-io-all
  namespace: qebbeq
spec:
  upstreamRegistry: docker.io
  # repository omitted (null) => applies to entire registry
  policy:
    type: ifNotPresent
  platforms:
    - linux/amd64
