{{- if .Values.registry.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qebbeq-registry.fullname" . }}
  labels:
    {{- include "qebbeq-registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.registry.service.type }}
  ports:
    - port: {{ .Values.registry.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "qebbeq-registry.selectorLabels" . | nindent 4 }}
{{- end -}}
